AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true

Metrics/MethodLength:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
